name: CI

# This workflow performs basic checks on each push and pull request. It
# verifies that the project can be installed and built on a clean
# environment.  It runs `npm install` in the root and mobile-app
# directories and invokes the Expo CLI to validate the managed app
# configuration.  If additional scripts (tests, lint) are added in the
# future, they can be included here as additional steps.

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install --no-audit --legacy-peer-deps

      - name: Install mobile app dependencies
        working-directory: mobile-app
        run: |
          npm install --no-audit --legacy-peer-deps

      - name: Install Expo CLI
        run: npm install --global expo-cli

      - name: Run Expo doctor
        working-directory: mobile-app
        run: npx expo doctor

      # If you add unit tests or a build step, include them here. For example:
      # - name: Run tests
      #   run: npm test